TheLaptopStore/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
using TheLaptopStore.Data;

namespace TheLaptopStore.Controllers {
    public class PaymentController : Controller {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;
        public PaymentController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<HomeController> logger, ApplicationDbContext db) {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _db = db;
        }

        public IActionResult RemoveProductCart(string? laptopModel) {
            string userId = _userManager.GetUserId(User);

            if (userId == null) {
                userId = HttpContext.Session.GetString("id");
            }

            ApplicationUser user = _db.Users.Find(userId);
            List<ShoppingCart> userCarts = _db.ShoppingCarts.Include(c => c.laptop).Where(cart => cart.userId == userId).ToList();
            foreach (ShoppingCart cart in userCarts) {
                if (cart.laptopModel == laptopModel) {
                    _db.ShoppingCarts.Remove(cart);
                    _db.SaveChanges();
                    return Redirect("~/ShoppingCart");
                }
            }
            return Redirect("~/ShoppingCart");
        }
        public IActionResult AddProductCart(string? laptopModel) {
            string userId = _userManager.GetUserId(User);

            if (userId == null) {
                userId = HttpContext.Session.GetString("id");
            }

            ApplicationUser user = _db.Users.Find(userId);
            List<ShoppingCart> userCarts = _db.ShoppingCarts.Include(c => c.laptop).Where(cart => cart.userId == userId).ToList();
            foreach (ShoppingCart cart in userCarts) {
                if (cart.laptopModel == laptopModel) {
                    if (_db.Laptops.Find(laptopModel).Quantity > cart.quantity) {
                        cart.quantity++;
                        cart.totalPrice = Convert.ToInt32(cart.quantity * (cart.laptop.Price - cart.laptop.Price * cart.laptop.SalePrecentage * 0.01));
                        _db.SaveChanges();
                        int price = 0;
                        var cartList = _db.ShoppingCarts.Include(c => c.laptop).Where(c => c.userId == userId).ToList();
                        foreach (var Cart in cartList) {
                            price += Cart.totalPrice;
                        }
                        TempData["Price"] = price;
                        return Redirect("~/ShoppingCart");
                    } else {
                        TempData["CantAdd"] = "Cant add another product";
                        TempData["idModel"] = _db.Laptops.Find(laptopModel).Model;

                        return Redirect("~/ShoppingCart");
                    }
                }
            }
            return Redirect("~/ShoppingCart");
        }

        public IActionResult DecreaseProductCart(string? laptopModel) {
            string userId = _userManager.GetUserId(User);

            if (userId == null) {
                userId = HttpContext.Session.GetString("id");
            }

            ApplicationUser user = _db.Users.Find(userId);
            List<ShoppingCart> userCarts = _db.ShoppingCarts.Include(c => c.laptop).Where(cart => cart.userId == userId).ToList();
            foreach (ShoppingCart cart in userCarts) {
                if (cart.laptopModel == laptopModel) {

                    if (cart.quantity > 1) {
                        cart.quantity--;
                        cart.totalPrice = Convert.ToInt32(cart.quantity * (cart.laptop.Price - cart.laptop.Price * cart.laptop.SalePrecentage * 0.01));
                        _db.SaveChanges();
                        int price = 0;
                        var cartList = _db.ShoppingCarts.Include(c => c.laptop).Where(c => c.userId == userId).ToList();
                        foreach (var Cart in cartList) {
                            price += Cart.totalPrice;
                        }
                        TempData["Price"] = price;

                        return Redirect("~/ShoppingCart");

                    } else {
                        _db.ShoppingCarts.Remove(cart);
                        _db.SaveChanges();
                        int price = 0;
                        var cartList = _db.ShoppingCarts.Include(c => c.laptop).Where(c => c.userId == userId).ToList();
                        foreach (var Cart in cartList) {
                            price += Cart.totalPrice;
                        }
                        TempData["Price"] = price;
                        return Redirect("~/ShoppingCart");
                    }
                }
            }
            return Redirect("~/ShoppingCart");
        }

        public IActionResult showPaymentPage() {
            string userId = _userManager.GetUserId(User);
            ApplicationUser user = _db.Users.Find(userId);

            if (userId == null) {
                userId = HttpContext.Session.GetString("id");
            }

            // Check if the shopping cart for the user exists
            ShoppingCart userCart = _db.ShoppingCarts.FirstOrDefault(cart => cart.userId == userId);

            if (userCart == null) {
                TempData["ModelError"] = "Add products to your cart";
                return Redirect("~/ShoppingCart");
            } else {
                List<ShoppingCart> userCarts = _db.ShoppingCarts.Include(c => c.laptop).Where(cart => cart.userId == userId).ToList();
                foreach (ShoppingCart cart in userCarts) {
                    if (_db.Laptops.Find(cart.laptop.Model).Quantity - cart.quantity < 0) {
                        TempData["UnavailableLaptop"] = "The product model : " + cart.laptop.Model + " is Unavailable";
                        _db.ShoppingCarts.Remove(cart);
                        _db.SaveChanges();
                        return Redirect("~/ShoppingCart");
                    }
                }
            }
            if (user == null) {
                return View("GuestPayment");
            }
            return View("PaymentPage", user);
        }

        public IActionResult payNow(string? cardNumber, string? expDate, string? CVV) {
            string userId = _userManager.GetUserId(User);

            string cardWithoutSpaces = cardNumber.Replace(" ", "");

            string[] parts = expDate.Split('/');
            int expMonth = int.Parse(parts[0]);
            int expYear = int.Parse("20" + parts[1]);

            if (userId == null) {
                userId = HttpContext.Session.GetString("id");
            }

            ApplicationUser user = _db.Users.Find(userId);

            if (user == null) {
                List<ShoppingCart> guestCarts = _db.ShoppingCarts.Include(c => c.laptop).Where(cart => cart.userId == userId).ToList();

                foreach (ShoppingCart cart in guestCarts) {
                    var product = _db.Laptops.Find(cart.laptop.Model);
                    product.Quantity -= cart.quantity;
                    product.PopularityIndex += cart.quantity;
                    _db.ShoppingCarts.Remove(cart);
                }

                _db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            List<ShoppingCart> userCarts = _db.ShoppingCarts.Include(c => c.laptop).Where(cart => cart.userId == userId).ToList();

            foreach (ShoppingCart cart in userCarts) {
                var product = _db.Laptops.Find(cart.laptop.Model);
                product.Quantity -= cart.quantity;
                product.PopularityIndex += cart.quantity;
                _db.ShoppingCarts.Remove(cart);
            }
            user.CreditCardNumber = long.Parse(cardWithoutSpaces);
            user.ExpDateMonth = expMonth;
            user.ExpDateYear = expYear;
            user.CVV = Convert.ToInt32(CVV);

            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

TheLaptopStore/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheLaptopStore.Data;

namespace TheLaptopStore.Controllers {
    public class ShoppingCartController : Controller {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;
        public ShoppingCartController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<HomeController> logger, ApplicationDbContext db) {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _db = db;
        }
        public IActionResult Index() {

            string id = _userManager.GetUserId(User);
            if (id == null) {
                id = HttpContext.Session.GetString("id");
            }
            int price = 0;
            var cartList = _db.ShoppingCarts.Include(c => c.laptop).Where(c => c.userId == id).ToList();
            foreach (var cart in cartList) {
                price += cart.totalPrice;

            }

            TempData["Price"] = price;
            return View("ShoppingCartPage", cartList);
        }

        public IActionResult cartItemsCounter() {
            string id = _userManager.GetUserId(User);
            if (id == null) {
                id = HttpContext.Session.GetString("id");
            }
            List<ShoppingCart> carts = _db.ShoppingCarts.Where(cart => cart.userId == id).ToList();
            int count1 = 0;

            foreach (var cart in carts) {
                count1 += cart.quantity;
            }

            return Ok(new { count = count1 });

        }
    }
}

TheLaptopStore/Views/ShoppingCart/ShoppingCartPage.cshtml
@{
    ViewData["Title"] = "ShoppingCartPage";
    var sessionId = TempData["idModel"];
}

<link rel="stylesheet" href="~/css/ShoppingCartPage.css">

<div class="container mt-5 p-3 rounded cart">
    <div class="row no-gutters">
        <div class="col-md-8">
            <div class="product-details mr-2">

                <hr>
                <h2 class="mb-0">Shopping cart</h2>
                <div class="d-flex justify-content-between">
                </div>
                <table class="table mt-3 items rounded">
                    <tr>
                        <th>Product</th>
                        <th>Model</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                    </tr>
                    @foreach (var cart in Model) {
                        <tr class="cart-row ">
                            <td>
                                <div class="d-flex flex-row align-items-center">
                                    <img class="rounded" src="~/photos/@(cart.laptop.Picture)" width="40">
                                </div>
                            </td>
                            <td>
                                <span class="font-weight-bold">@cart.laptop.Model</span>
                            </td>
                            <td>
                                <span class="quantity-value">@cart.quantity</span>
                                <a href="@Url.Action("AddProductCart", "Payment", new { laptopModel = cart.laptopModel })" class="quantity-link" onclick="changeQuantity('@cart.laptopModel', 'increase')">&#9650;</a>
                                <a href="@Url.Action("DecreaseProductCart", "Payment", new { laptopModel = cart.laptopModel })" class="quantity-link" onclick="changeQuantity('@cart.laptopModel', 'decrease')">&#9660;</a>
                            </td>
                            <td>
                                <span class="font-weight-bold">@cart.totalPrice</span>
                            </td>
                            <td>
                                <i class="fa fa-trash-o text-black-50"></i>
                            </td>
                            <td>
                                <a class="btn btn-primary" href="@Url.Action("RemoveProductCart", "Payment", new { laptopModel = cart.laptopModel })" role="button">Remove</a><br />
                            </td>
                            <td>
                                @if (sessionId != null) {
                                    @if (cart.laptopModel == sessionId.ToString()) {
                                        <span id="cantAddMessage" class="font-weight-bold">@TempData["CantAdd"]</span>

                                        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
                                        <script>
                                            $(document).ready(function () {
                                                // Set the duration in milliseconds (e.g., 1000 for 1 second)
                                                var duration = 1000;

                                                // Hide the message after the specified duration
                                                setTimeout(function () {
                                                    $("#cantAddMessage").fadeOut();
                                                }, duration);
                                            });
                                        </script>
                                    }
                                }
                            </td>
                        </tr>
                    }



                </table>
                @{
                    var modelError = TempData["ModelError"] as string;
                }
                <a class="btn btn-primary" href="@Url.Action("showPaymentPage", "Payment")" role="button">Checkout</a><br />
                <span id="modelError" class="text-danger">@modelError</span><br />
                <span class="font-weight-bold">Total price:  @TempData["Price"]</span><br />
                <span id="modelError" class="text-danger">@TempData["UnavailableLaptop"]</span><br />
            </div>
        </div>
    </div>
</div>