TheLaptopStore/Controllers/ProductPageController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TheLaptopStore.Data;

namespace TheLaptopStore.Controllers {
    public class ProductPageController : Controller {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;
        public ProductPageController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<HomeController> logger, ApplicationDbContext db) {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _db = db;
        }

        public IActionResult showProductCard(string? model) {
            var obj = _db.Laptops.Find(model);

            if (obj == null) {
                return NotFound();
            }
            return View("ProductCard", obj);
        }

        public IActionResult AddToCart(string? model, string addToCart, string buyNow) {

            string id = _userManager.GetUserId(User);
            var laptop = _db.Laptops.Find(model);

            if (id == null) {
                id = HttpContext.Session.GetString("id");
            }

            if (laptop == null) {
                return NotFound();
            }
            string quan = Request.Form["quantity"];

            if (quan == "" || Convert.ToInt32(quan) <= 0) {
                TempData["NagtiveNumber"] = "Quantity must be positive";
                return View("ProductCard", laptop);
            }

            if (!string.IsNullOrEmpty(quan) && laptop.Quantity < Convert.ToInt32(Request.Form["quantity"])) {
                TempData["TooMuchProducts"] = "Only " + laptop.Quantity + " laptops left";
                return View("ProductCard", laptop);
            }
            if (string.IsNullOrEmpty(quan)) {
                TempData["EmptyQuantity"] = "Add products";
                return View("ProductCard", laptop);
            }


            ShoppingCart sc = _db.ShoppingCarts.Find(model, id);
            if (sc is not null) {
                int checkQuantity = sc.quantity + Convert.ToInt32(Request.Form["quantity"]);
                if (checkQuantity > laptop.Quantity) {
                    TempData["cartPlusQuantity"] = "You have in your cart " + sc.quantity + "\nThere is left: " + (laptop.Quantity - sc.quantity);
                    return View("ProductCard", laptop);
                }
                sc.quantity += Convert.ToInt32(Request.Form["quantity"]);
                sc.totalPrice = sc.quantity * laptop.Price;
            } else {
                int totalPrice = 0;
                int quantity = Convert.ToInt32(Request.Form["quantity"]);
                if (laptop.SalePrecentage > 0) {
                    totalPrice = Convert.ToInt32(quantity * (laptop.Price - laptop.Price * (laptop.SalePrecentage * 0.01)));
                } else {
                    totalPrice = quantity * laptop.Price;
                }
                ShoppingCart cart = new ShoppingCart();
                cart.laptop = laptop;
                cart.laptopModel = model;
                cart.totalPrice = totalPrice;
                cart.quantity = quantity;
                cart.userId = id;

                _db.ShoppingCarts.Add(cart);
            }
            _db.SaveChanges();
            if (!string.IsNullOrEmpty(addToCart)) {
                return RedirectToAction("Index", "Home");
            } else {

                return Redirect("~/ShoppingCart"); // Redirect to the checkout page or any other appropriate action
            }

        }



    }
}

TheLaptopStore/Views/ProductPage/ProductCard.cshtml
@model TheLaptopStore.Data.Laptop
@using TheLaptopStore.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "ProductCard";
}
<style>
    button.waitlist-button {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

        button.waitlist-button:hover {
            background-color: #0056b3; /* Darker shade on hover */
        }

    a.waitlist-a {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

        a.waitlist-a:hover {
            background-color: #0056b3; /* Darker shade on hover */
        }
</style>
<body style="background-color: #E1EBEE">
    <div class="container">
        <div class="col-lg-12 border p-3 main-section bg-white ">
            <div class="row m-0">
                <div class="col-lg-4 left-side-product-box pb-3  ">
                    <img src="~/photos/@Model.Picture" class="img-fluid img-thumbnail" style="width: 100%;" alt="Laptop Image">
                </div>
                <div class="col-lg-8 ">
                    <div class="right-side-pro-detail border p-3 m-0 ">
                        <div class="row">
                            <div class="col-lg-12 ">
                                <span><strong>@Model.Maker</strong></span>
                                <p class="m-0 p-0"><strong>@Model.Model</strong></p>
                            </div>
                            <div class="col-lg-12 ">
                                <div class="d-inline-flex justify-content-between align-items-center">
                                    <strong><h3>@((int)(Math.Floor(Model.Price - Model.Price * (Model.SalePrecentage * 0.01)))) $</h3></strong>
                                    @if (Model.SalePrecentage > 0) {
                                        <div id="old-price" class="ml-3" style="text-decoration: line-through; margin-left: 30px; "><h5>@Model.Price $</h5></div>
                                        <div style="margin-left: 15px;">- @Model.SalePrecentage %</div>
                                    }
                                </div>
                                <hr class="p-0 m-0">
                            </div>
                            <div class="col-lg-12 pt-2 ">
                                <h5><strong>Description: </strong></h5>
                                <span>@Model.Description</span>

                            </div>
                            <div class="col-lg-12 pt-3  ">
                                <p class="tag-section"><strong>Category: </strong>@Model.Category</p>
                                <p class="tag-section"><strong>Ram: </strong>@Model.Ram GB</p>
                                <p class="tag-section"><strong>SSD: </strong>@Model.SSD GB</p>
                                <p class="tag-section"><strong>GPU: </strong>@Model.GPU</p>
                                <p class="tag-section"><strong>Screen Size: </strong>@Model.ScreenSize "</p>
                                <p class="tag-section"><strong>Color: </strong>@Model.Color</p>
                                <p class="tag-section"><strong>Release Date: </strong>@Model.ReleaseDate</p>
                            </div>
                            <div class="col-lg-12  ">
                                <h6><strong>Quantity in stock: </strong>@Model.Quantity</h6>
                                @if (Model.Quantity > 0) {
                                    <form asp-action="AddToCart" asp-controller="ProductPage">
                                        <input id="quantity" name="quantity" type="number" placeholder="Choose Quantity" />
                                        <span id="NagtiveNumber" class="text-danger">@TempData["NagtiveNumber"]</span>
                                        <span id="EmptyQuantity" class="text-danger">@TempData["EmptyQuantity"]</span>
                                        <span id="TooMuchProducts" class="text-danger">@TempData["TooMuchProducts"]</span>
                                        <span id="cartPlusQuantity" class="text-danger">@TempData["cartPlusQuantity"]</span>
                                        <input type="hidden" id="model" name="model" value="@Model.Model" />

                                        <!-- Adjusted structure with div elements -->
                                        <div class="row" >
                                            <div class="col-lg-12 mt-3">
                                                <div class="row ">
                                                    <div class="col-lg-6 pb-2 ">
                                                        <input class="btn btn-danger w-100" name="addToCart" id="addToCart" type="submit" value="Add to Cart" />
                                                    </div>
                                                    <div class="col-lg-6 ">
                                                        <input class="btn btn-success w-100" name="buyNow" id="buyNow" type="submit" value="buyNow" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                } else {
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <p>Sorry, this product is currently out of stock.</p>
                                        <a asp-controller="AdminPage" asp-action="editProduct" asp-route-model="@Model.Model"  id="addQuantity" type="submit" class="waitlist-a">Add products</a>
                                    }
                                    else
                                    {
                                        @if (SignInManager.IsSignedIn(User)==false)
                                        {
                                            <p>Sorry, this product is currently out of stock.</p>
                                            <a asp-area ="Identity" asp-page="/Account/Login" class="waitlist-a">Register for waiting list</a>
                                           
                                        }
                                        else
                                        {
                                            <p>Sorry, this product is currently out of stock.</p>
                                            <button id="NoQuantity" class="waitlist-button">Add me to wait-list</button>
                                        }
                                    }
                                }
                            </div>

                            <script>
                                document.getElementById("NoQuantity").addEventListener("click", function () {
                                    alert("You have been added to the wait-list!");
                                });
                            </script>

                        </div>
                    </div>
                </div>
            </div>
        </div>
     
    </div>
</body>